from PIL import Image

# Path to the original uncropped square image generated by the AI
orig_path = r"C:\Users\m.h\.gemini\antigravity-ide\brain\ca36d41d-ebaf-40f2-9e63-d1acf39703e4\vibe_shooter_simple_logo_1786496032637.png"
img = Image.open(orig_path).convert("RGBA")

# Get the background color from the top-left pixel to ensure a seamless match
bg_color = img.getpixel((0, 0))

# Create a 1200x630 background with that exact color
bg = Image.new('RGBA', (1200, 630), color=bg_color)

# Resize the original image so it fits perfectly in the height
new_size = 630
img_resized = img.resize((new_size, new_size), Image.Resampling.LANCZOS)

# Paste the resized original image in the center
offset = ((1200 - new_size) // 2, 0)
bg.paste(img_resized, offset)

# Save the final og-image
bg.convert('RGB').save('og-image.png', optimize=True, quality=90)
print("Saved og-image.png with matching background")
